CONNECT TO AI2 USER "db2admin" USING ;
CREATE TABLE DB2ADMIN.NEWS ( ID INTEGER  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , PUBLISH_DATE DATE  NOT NULL , START_DATE DATE  NOT NULL , END_DATE DATE  NOT NULL , PUBLISH SMALLINT  NOT NULL  WITH DEFAULT 0 , LINK VARCHAR (100)  NOT NULL , HEADLINE VARCHAR (100)  NOT NULL , SUMMARY VARCHAR (2000)  NOT NULL , STORY VARCHAR (10000)  NOT NULL   ) ;
CONNECT RESET;
