#!/usr/bin/perl -w
 
use strict;
use CGI qw(:standard);
use URI::Escape;

my $inputline;
my @queryvalues;

print "Content-type: text/html\n\n";
print "<HTML>\n<HEAD>\n<TITLE>DIG - Domain Information Groper\n</TITLE>\n</HEAD>\n<BODY>\n";

   print <<END_OF_INITIAL;
<center><H1>DIG - Domain Information Groper</H1></center>
<blockquote>
<form ACTION="/cgi/dig" METHOD=POST>
<pre>
Name Server: <input TYPE="text" NAME="host" SIZE=36 >

Domain Name: <input TYPE="text" NAME="domain" SIZE=36 >

Query Type:  <select NAME="type">
             <option VALUE="A"> Address (A)
             <option VALUE="PTR"> Pointer (PTR)
             <option VALUE="MX"> Mail Exchange (MX)
             <option VALUE="NS"> Name Server (NS)
             <option VALUE="SOA"> Start Of Authority (SOA)
             <option VALUE="HINFO"> Host Info (HINFO)
             <option VALUE="TXT"> Text (TXT)
             <option VALUE="ANY"> Any (ANY)
             <option VALUE="AXFR"> Zone Transfer (AXFR)
             </select>

<input TYPE="SUBMIT" VALUE="Perform query">

<hr>
</pre>
</form>
</blockquote>
END_OF_INITIAL

if ($ENV{'REQUEST_METHOD'} eq "POST") {
     $inputline = <STDIN>;
     @queryvalues = split(/&/,$inputline);
} 
print "@queryvalues";

print "</BODY>\n</HTML>\n";
