#!/usr/bin/perl -w

use strict;

sub numerically { 
   my ($a, $b) = @_;
   return $a <=> $b;
}

sub HighRoller {
   my ($dice, $sum);
   
   $dice = int(rand(36));
   
   if ( $dice < 1 ) {
      $sum = 2;
   } elsif ( $dice < 3 ) {
      $sum = 3;
   } elsif ( $dice < 6 ) {
      $sum = 4;
   } elsif ( $dice < 10 ) {
      $sum = 5;
   } elsif ( $dice < 15 ) {
      $sum = 6;
   } elsif ( $dice < 21 ) {
      $sum = 7;
   } elsif ( $dice < 26 ) {
      $sum = 8;
   } elsif ( $dice < 30 ) {
      $sum = 9;
   } elsif ( $dice < 33 ) {
      $sum = 10;
   } elsif ( $dice < 35 ) {
      $sum = 11;
   } elsif ( $dice == 35 ) {
      $sum = 12;
   } else {
      print "Oops\n";
   }
   
   return $sum;
}

my %diceRolls = ();
my $sum = 0;
my ($temp, $key);

srand();
   
for (my $i=0; $i < 200000; $i++) {
   $sum = HighRoller();
   if ( exists($diceRolls{$sum}) ) {
      $diceRolls{$sum} += 1;
   } else {
      $diceRolls{$sum} = 1;
   }   
}

for ( my $i = 2; $i <= 12; $i++ ) {
   print "$i: $diceRolls{$i}\n";
}
