#!/usr/bin/perl -w

use strict;

my ($coin, $tails, $heads);
$heads = 0;
$tails = 0;

srand();
   
for (my $i=0; $i < 100000; $i++) {
   $coin = int(rand(7));
   if ($coin < 5) {
      $heads++;
   } else {
      $tails++;
   }
}

print "Heads: $heads, Tails: $tails\n";