<?php

$code39_table = array(
    '0' => 'nnnwwnwnn',
    '1' => 'wnnwnnnnw',
    '2' => 'nnwwnnnnw',
    '3' => 'wnwwnnnnn',
    '4' => 'nnnwwnnnw',
    '5' => 'wnnwwnnnn',
    '6' => 'nnwwwnnnn',
    '7' => 'nnnwnnwnw',
    '8' => 'wnnwnnwnn',
    '9' => 'nnwwnnwnn',
    'A' => 'wnnnnwnnw',
    'B' => 'nnwnnwnnw',
    'C' => 'wnwnnwnnn',
    'D' => 'nnnnwwnnw',
    'E' => 'wnnnwwnnn',
    'F' => 'nnwnwwnnn',
    'G' => 'nnnnnwwnw',
    'H' => 'wnnnnwwnn',
    'I' => 'nnwnnwwnn',
    'J' => 'nnnnwwwnn',
    'K' => 'wnnnnnnww',
    'L' => 'nnwnnnnww',
    'M' => 'wnwnnnnwn',
    'N' => 'nnnnwnnww',
    'O' => 'wnnnwnnwn',
    'P' => 'nnwnwnnwn',
    'Q' => 'nnnnnnwww',
    'R' => 'wnnnnnwwn',
    'S' => 'nnwnnnwwn',
    'T' => 'nnnnwnwwn',
    'U' => 'wwnnnnnnw',
    'V' => 'nwwnnnnnw',
    'W' => 'wwwnnnnnn',
    'X' => 'nwnnwnnnw',
    'Y' => 'wwnnwnnnn',
    'Z' => 'nwwnwnnnn',
    '-' => 'nwnnnnwnw',
    '.' => 'wwnnnnwnn',
    ' ' => 'nwwnnnwnn',
    '*' => 'nwnnwnwnn',
    '$' => 'nwnwnwnnn',
    '/' => 'nwnwnnnwn',
    '+' => 'nwnnnwnwn',
    '%' => 'nnnwnwnwn',
);

$code39_widths = array(
    'w' => 2,
    'n' => 1,
);

?>