#!/usr/bin/perl -w

use strict;

my $test = 0;
my $n = 1;
while ($test < 20) {
    my $i = 1;
    #print "$n ";
    while ($i <= 20) {
       if ($n % $i == 0) {
          #print "$i ";
          $test += 1;
       } 
       $i++;
    }
    #print "\n";
    if ($test < 20) {
       $test = 0;
    } else {
       print "$n is divisible by all numbers under 20\n";
    }
    $n++;
}
