#!/usr/bin/perl -w

use strict;

my ($i, $j, $x, $sum, %hash);
$i = $j = $sum = 0;

while ( $i < 1000 ) {
   if ($i * 3 < 1000) {
      $hash{$i * 3} = 1;
   }
   if ($i * 5 < 1000) {
      $hash{$i * 5} = 1;
   }
   $i += 1;
}

foreach $x (sort(keys(%hash))) {
   print "$x \n";
   $sum += $x;
}
print "Sum of multiples of 3 and 5 less than 1000 is $sum\n";
