#!/bin/bash

low=""
high=""

while read line; do
   if [ "$low" = "" ]; then
      low=$line
   fi
   if [ "$high" = "" ]; then
      high=$line
   fi
   if [ "$low" -gt "$line" ]; then
      low=$line
   fi

   if [ "$high" -lt "$line" ]; then
      high=$line
   fi
done < $1

echo "Lowest ${low}"
echo "Highest ${high}"
