#!/bin/bash

if [ ! -e "myfile" ]; then
   touch myfile
fi

echo "File myfile exists, shall I delete it? "
read input
if [ "$input" = "y" ] || [ "$input" = "yes" ]; then
   rm myfile 
   exit 0
fi
if [ "$input" = "n" ] || [ "$input" = "no" ]; then
   exit 0 
fi

count=0
while [ "$count" -lt "3" ]; do
   echo "Valid input choices are yes or y, no or n"
   read input
   if [ "$input" = "y" ] || [ "$input" = "yes" ]; then
      rm myfile 
      exit 0
   fi
   if [ "$input" = "n" ] || [ "$input" = "no" ]; then
      exit 0 
   fi
   count=`expr $count + 1`
done
echo "Too many mistakes. When you learn to read and/or type get back to me. :)" 
