extern	int main(int argc, char *argv[]);
extern	void readfile(char *name);
extern	int check(void);
extern	void getmove(void);
extern	void init(int obdflag,int handicapflag);
extern	void g2exit(int i);
extern	void fixplaylevel(int p);
extern	void initinit(int l, int s);
extern	void turnoffcplay(void);
extern	void outerror(int line,char *str);
extern	void psqr(int s);
extern	void ssqr(int s,char *str);
